#######################################################
# 
# PostTopic.py
# Python implementation of the Class PostTopic
# Generated by Enterprise Architect
# Created on:      10-Nov-2024 19:49:23
# Original author: enbysenpai
# 
#######################################################
from TopicModeler import TopicModeler

class PostTopic:
    def __init__(self, post_details, topics):
        self.post_details = post_details
        self.topics = topics

    def to_dict(self):
        return self.__dict__