#######################################################
# 
# Preprocessor.py
# Python implementation of the Class Preprocessor
# Generated by Enterprise Architect
# Created on:      10-Nov-2024 00:31:21
# Original author: enbysenpai
# 
#######################################################


class Preprocessor:
    def preprocess(data):
        pass