#######################################################
# 
# TopicModeler.py
# Python implementation of the Class TopicModeler
# Generated by Enterprise Architect
# Created on:      10-Nov-2024 00:31:21
# Original author: enbysenpai
# 
#######################################################
from Preprocessor import Preprocessor

class TopicModeler:
    m_Preprocessor= Preprocessor()

    def extract_topics(data):
        pass