#######################################################
# 
# LanguageSupport.py
# Python implementation of the Class LanguageSupport
# Generated by Enterprise Architect
# Created on:      08-Nov-2024 20:29:15
# Original author: enbysenpai
# 
#######################################################


class LanguageSupport:
    def detectLanguage(self):
        pass

    def translate(self):
        pass