#######################################################
# 
# SentimentModel.py
# Python implementation of the Class SentimentModel
# Generated by Enterprise Architect
# Created on:      08-Nov-2024 20:29:15
# Original author: enbysenpai
# 
#######################################################


class SentimentModel:
    def predictSentiment(self):
        pass

    def trainModel(self):
        pass