#######################################################
# 
# SentimentScore.py
# Python implementation of the Class SentimentScore
# Generated by Enterprise Architect
# Created on:      08-Nov-2024 20:29:15
# Original author: enbysenpai
# 
#######################################################


class SentimentScore:
    pass
