#######################################################
# 
# SentimentAnalyzer.py
# Python implementation of the Class SentimentAnalyzer
# Generated by Enterprise Architect
# Created on:      08-Nov-2024 20:29:15
# Original author: enbysenpai
# 
#######################################################
from Package1.SentimentModel import SentimentModel
from Package1.SentimentScore import SentimentScore
from Package1.LanguageSupport import LanguageSupport

class SentimentAnalyzer:
    m_SentimentModel= SentimentModel()

    m_SentimentScore= SentimentScore()

    m_LanguageSupport= LanguageSupport()

    def classifySentiment() -> void:
        pass

    def detectEmotion() -> void:
        pass

    def performSentimentAnalysis() -> void:
        pass