#######################################################
# 
# SentimentAnalyzer.py
# Python implementation of the Class SentimentAnalyzer
# Generated by Enterprise Architect
# Created on:      08-Nov-2024 20:29:15
# Original author: enbysenpai
# 
#######################################################
from api.mdd.mdd2.SentimentModel import SentimentModel
from api.mdd.mdd2.SentimentScore import SentimentScore
from api.mdd.mdd2.LanguageSupport import LanguageSupport

class SentimentAnalyzer:
    m_SentimentModel= SentimentModel()

    m_SentimentScore= SentimentScore()

    m_LanguageSupport= LanguageSupport()

    def classifySentiment(self):
        pass

    def detectEmotion(self):
        pass

    def performSentimentAnalysis(self):
        pass