#######################################################
# 
# LexiconSentimentModel.py
# Python implementation of the Class LexiconSentimentModel
# Generated by Enterprise Architect
# Created on:      11-Nov-2024 11:16:01 PM
# Original author: stefan
# 
#######################################################
from .SentimentAnalyzer import SentimentAnalyzer

from nltk.sentiment.vader import SentimentIntensityAnalyzer


class LexiconBasedAnalyzer(SentimentAnalyzer):
    def __init__(self):
        super().__init__()
        self.analyzer = SentimentIntensityAnalyzer()

    def analyze(self, text):
        sentiment_scores = self.analyzer.polarity_scores(text)
        return sentiment_scores
