#######################################################
# 
# LexiconBasedAnalyzer.py
# Python implementation of the Class LexiconBasedAnalyzer
# Generated by Enterprise Architect
# Created on:      11-Nov-2024 11:16:01 PM
# Original author: stefan
# 
#######################################################
from .SentimentAnalyzer import SentimentAnalyzer

class LexiconBasedAnalyzer(SentimentAnalyzer):
    def __init__(self):
        super().__init__()
        self.lexicon = {}

    def analyze(self, text):
        pass

    def load_lexicon(self, lexicon_path):
        pass
