#######################################################
# 
# SentimentAnalyzer.py
# Python implementation of the Interface SentimentAnalyzer
# Generated by Enterprise Architect
# Created on:      11-Nov-2024 11:16:01 PM
# Original author: stefan
# 
#######################################################


class SentimentAnalyzer:
    def __init__(self):
        self.method = None

    def analyze(self, text):
        pass

    def set_method(self, method):
        pass
