#######################################################
# 
# Preprocessor.py
# Python implementation of the Class Preprocessor
# Generated by Enterprise Architect
# Created on:      10-Nov-2024 00:04:28
# Original author: enbysenpai
# 
#######################################################


class Preprocessor:
    def deleteEmojis(self, data):
        pass

    def removeTagsBrackets(self, data):
        pass

    def tokenize(self, data):
        pass

    def removePunctuation(self, data):
        pass

    def removeStopwords(self, data):
        pass