#######################################################
# 
# TopicModeler.py
# Python implementation of the Class TopicModeler
# Generated by Enterprise Architect
# Created on:      10-Nov-2024 10:50:55
# Original author: enbysenpai
# 
#######################################################
from pydoc_data.topics import topics

from numpy.lib.function_base import extract

from Preprocessor import Preprocessor
from gensim import corpora
from gensim.models import LdaModel

class TopicModeler:

    def __init__(self, data):
        self.data = data
        self.processed_data = Preprocessor(self.data).preprocess()

    # using LDA
    # TODO: the implementation of LDA without libraries (later)
    def extract_topics(self):
        dictionary = corpora.Dictionary(self.processed_data)
        corpus = [dictionary.doc2bow(text) for text in self.processed_data]

        lda_model = LdaModel(corpus, num_topics=2, id2word=dictionary, passes=15)

        topics = lda_model.print_topics(num_words=3)
        for topic in topics:
            print(topic)




